/**
 * dsh-dock — Client(web) 构建脚本
 *
 * 产物契约（DSH client-modules，与 dsh-token-usage 的 client/build.mjs 同款）：
 *   window.__ModuleLoader__.load({ id: "dsh-dock", factory: (require) => { ... return module.exports } })
 * - classic <script> 加载，factory 是 CJS 闭包，接收运行时 require
 * - react / react/jsx-runtime 由运行时 seed，构建时外部化
 * - 源码：src/client.jsx（面板外壳）+ src/shared.js + features 各模块的 view.js(x)（功能模块），
 *   bundle 成单文件 client.js（构建产物，提交仓库、随包发布；勿手改）
 *
 * 构建：node scripts/build-client.mjs   （内部调用 npx esbuild，无需本地安装依赖）
 */
import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, rmSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const src = join(root, "src", "client.jsx");
const outFile = join(root, "client.js");
const tmpFile = join(root, "client.tmp.cjs");
const PACKAGE_ID = "dsh-dock";

function runEsbuild(args) {
  // npx 自动解析 esbuild（含 npx 缓存）；Windows 下经 shell 调用
  // stdio: inherit — esbuild 输出直通终端，不捕获管道（沙箱/CI 下避免管道 EPERM）
  try {
    execSync(`npx --yes esbuild ${args.map((a) => JSON.stringify(a)).join(" ")}`, {
      stdio: "inherit",
      shell: process.platform === "win32",
    });
  } catch (e) {
    throw new Error(`esbuild failed: ${e.message || e}`);
  }
}

// 1) bundle + 转译 → CJS（react 系外部化：运行时 seed 提供 require("react") / require("react/jsx-runtime")）
runEsbuild([
  src,
  "--bundle",
  "--format=cjs",
  "--platform=browser",
  "--jsx=automatic",
  "--loader:.js=jsx",
  "--external:react",
  "--external:react/jsx-runtime",
  "--outfile=" + tmpFile,
  "--log-level=warning",
]);

// 2) 包 ModuleLoader 工厂壳（esbuild 产物里的自由变量 module/exports/require 落到壳的闭包上）
const banner = `/* dsh-dock client bundle — generated by scripts/build-client.mjs（源码：src/ + features/，勿手改本文件） */
window.__ModuleLoader__.load({
	id: ${JSON.stringify(PACKAGE_ID)},
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
`;
const footer = `
		exports.apply = apply;
		exports.inject = inject;
		exports.dockBridge = dockBridge;
		return module.exports;
	}
});
`;
const inner = readFileSync(tmpFile, "utf8");
writeFileSync(outFile, banner + inner + "\n" + footer, "utf8");
rmSync(tmpFile, { force: true });
console.log("built:", outFile, "bytes:", (banner + inner + "\n" + footer).length);
